#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
porti=$(ynh_app_setting_get --app=$app --key=porti)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- $port$"
then
	ynh_exec_warn_less yunohost firewall disallow TCP $port
fi
